"""Admin platform domain events."""

MERCHANT_APPROVED = "merchant.approved"
MERCHANT_SUSPENDED = "merchant.suspended"
MERCHANT_UNSUSPENDED = "merchant.unsuspended"
MERCHANT_REOPENED = "merchant.reopened"
MERCHANT_CLOSED = "merchant.closed"
DRIVER_CREATED = "driver.created"
DRIVER_APPROVED = "driver.approved"
DRIVER_SUSPENDED = "driver.suspended"
DRIVER_REJECTED = "driver.rejected"
DRIVER_REHIRED = "driver.rehired"
CLAIM_OPENED = "claim.opened"
CLAIM_RESOLVED = "claim.resolved"
TICKET_CREATED = "support.ticket_created"
DISPATCH_ASSIGNED = "dispatch.assigned"
REFUND_APPROVED = "refund.approved"
