"""Backward-compatible re-exports — prefer `schemas_booking` in new code (§3.2.13)."""

from porterchain_api.schemas_booking import (
    AddressInput,
    BookingConfirmationResponse,
    BookingConfirmationStatusResponse,
    BookingDraftAuditItem,
    BookingDraftDetailResponse,
    BookingDraftResponse,
    BookingResponse,
    CheckoutMockCompleteRequest,
    CreateBookingDraftRequest,
    CreateQuoteRequest,
    CustomerDashboardResponse,
    CustomerRebookResponse,
    CustomerSupportTicketRequest,
    CustomerSupportTicketResponse,
    OrderResponse,
    OrderTrackingResponse,
    PaymentResponse,
    PaymentRetryRequest,
    PricingLineItem,
    QuoteResponse,
    StartBookingRequest,
    UpdateBookingDraftRequest,
    VisitorTrackingInput,
    WebsitePricingSnapshot,
)

__all__ = [
    "AddressInput",
    "BookingConfirmationResponse",
    "BookingConfirmationStatusResponse",
    "BookingDraftAuditItem",
    "BookingDraftDetailResponse",
    "BookingDraftResponse",
    "BookingResponse",
    "CheckoutMockCompleteRequest",
    "CreateBookingDraftRequest",
    "CreateQuoteRequest",
    "CustomerDashboardResponse",
    "CustomerRebookResponse",
    "CustomerSupportTicketRequest",
    "CustomerSupportTicketResponse",
    "OrderResponse",
    "OrderTrackingResponse",
    "PaymentResponse",
    "PaymentRetryRequest",
    "PricingLineItem",
    "QuoteResponse",
    "StartBookingRequest",
    "UpdateBookingDraftRequest",
    "VisitorTrackingInput",
    "WebsitePricingSnapshot",
]
