"""initial_schema

Revision ID: bd830e39ef4e
Revises: 
Create Date: 2026-06-30 10:54:12.364475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd830e39ef4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abandoned_checkouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_checkouts_quote_id'), 'abandoned_checkouts', ['quote_id'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fleetbase_user_uuid', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_clerk_user_id'), 'admin_users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_admin_users_fleetbase_user_uuid'), 'admin_users', ['fleetbase_user_uuid'], unique=False)
    op.create_table('billing_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_ledger_entries_kind'), 'billing_ledger_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_billing_ledger_entries_merchant_id'), 'billing_ledger_entries', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_billing_ledger_entries_order_id'), 'billing_ledger_entries', ['order_id'], unique=False)
    op.create_index(op.f('ix_billing_ledger_entries_payment_id'), 'billing_ledger_entries', ['payment_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('claim_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_order_id'), 'claims', ['order_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('crm_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_activities_activity_type'), 'crm_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_crm_activities_entity_id'), 'crm_activities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_entity_type'), 'crm_activities', ['entity_type'], unique=False)
    op.create_table('crm_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('operating_name', sa.String(length=255), nullable=True),
    sa.Column('business_number', sa.String(length=64), nullable=True),
    sa.Column('hst_number', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('business_type', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('branches', sa.JSON(), nullable=False),
    sa.Column('warehouse_locations', sa.JSON(), nullable=False),
    sa.Column('pickup_locations', sa.JSON(), nullable=False),
    sa.Column('billing_details', sa.JSON(), nullable=False),
    sa.Column('estimated_deliveries_per_month', sa.Integer(), nullable=True),
    sa.Column('estimated_monthly_revenue_cents', sa.Integer(), nullable=True),
    sa.Column('preferred_vehicle', sa.String(length=64), nullable=True),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('current_logistics_provider', sa.String(length=255), nullable=True),
    sa.Column('merchant_status', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_companies_email'), 'crm_companies', ['email'], unique=False)
    op.create_index(op.f('ix_crm_companies_industry'), 'crm_companies', ['industry'], unique=False)
    op.create_index(op.f('ix_crm_companies_legal_name'), 'crm_companies', ['legal_name'], unique=False)
    op.create_index(op.f('ix_crm_companies_merchant_id'), 'crm_companies', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_crm_companies_merchant_status'), 'crm_companies', ['merchant_status'], unique=False)
    op.create_index(op.f('ix_crm_companies_owner_id'), 'crm_companies', ['owner_id'], unique=False)
    op.create_table('crm_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_number', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('net_terms', sa.String(length=16), nullable=False),
    sa.Column('sla', sa.JSON(), nullable=False),
    sa.Column('service_areas', sa.JSON(), nullable=False),
    sa.Column('vehicles', sa.JSON(), nullable=False),
    sa.Column('insurance', sa.JSON(), nullable=False),
    sa.Column('pricing_sheet_url', sa.String(length=512), nullable=True),
    sa.Column('signed_document_url', sa.String(length=512), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('value_cents', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('renewal_reminder_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contracts_company_id'), 'crm_contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_contracts_contract_number'), 'crm_contracts', ['contract_number'], unique=False)
    op.create_index(op.f('ix_crm_contracts_deal_id'), 'crm_contracts', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_contracts_status'), 'crm_contracts', ['status'], unique=False)
    op.create_table('crm_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_documents_category'), 'crm_documents', ['category'], unique=False)
    op.create_index(op.f('ix_crm_documents_entity_id'), 'crm_documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_documents_entity_type'), 'crm_documents', ['entity_type'], unique=False)
    op.create_table('crm_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('net_terms', sa.String(length=16), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_invoices_company_id'), 'crm_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_invoices_invoice_number'), 'crm_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_crm_invoices_status'), 'crm_invoices', ['status'], unique=False)
    op.create_table('crm_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('business_type', sa.String(length=64), nullable=True),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('estimated_deliveries_per_month', sa.Integer(), nullable=True),
    sa.Column('estimated_revenue_cents', sa.Integer(), nullable=True),
    sa.Column('preferred_vehicle', sa.String(length=64), nullable=True),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('current_logistics_provider', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_assigned_to'), 'crm_leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_crm_leads_company_id'), 'crm_leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_company_name'), 'crm_leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_crm_leads_deal_id'), 'crm_leads', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_email'), 'crm_leads', ['email'], unique=False)
    op.create_index(op.f('ix_crm_leads_source'), 'crm_leads', ['source'], unique=False)
    op.create_index(op.f('ix_crm_leads_status'), 'crm_leads', ['status'], unique=False)
    op.create_table('crm_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_notes_entity_id'), 'crm_notes', ['entity_id'], unique=False)
    op.create_table('crm_quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_number', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_quotations_company_id'), 'crm_quotations', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_quotations_deal_id'), 'crm_quotations', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_quotations_quote_number'), 'crm_quotations', ['quote_number'], unique=False)
    op.create_index(op.f('ix_crm_quotations_status'), 'crm_quotations', ['status'], unique=False)
    op.create_table('crm_sales_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=128), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sales_tasks_assigned_to'), 'crm_sales_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_crm_sales_tasks_company_id'), 'crm_sales_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_sales_tasks_deal_id'), 'crm_sales_tasks', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_sales_tasks_entity_id'), 'crm_sales_tasks', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_sales_tasks_status'), 'crm_sales_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_crm_sales_tasks_task_type'), 'crm_sales_tasks', ['task_type'], unique=False)
    op.create_table('crm_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tasks_lead_id'), 'crm_tasks', ['lead_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_merchant_id'), 'crm_tasks', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_status'), 'crm_tasks', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('visitor_session_id', sa.String(length=64), nullable=True),
    sa.Column('customer_reference', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_clerk_user_id'), 'customers', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_customers_customer_reference'), 'customers', ['customer_reference'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_visitor_session_id'), 'customers', ['visitor_session_id'], unique=False)
    op.create_table('domain_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_aggregate_id'), 'domain_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_table('driver_stop_meta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_stop_meta_driver_id'), 'driver_stop_meta', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_stop_meta_order_id'), 'driver_stop_meta', ['order_id'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('license_verified', sa.Boolean(), nullable=False),
    sa.Column('insurance_verified', sa.Boolean(), nullable=False),
    sa.Column('vehicle_verified', sa.Boolean(), nullable=False),
    sa.Column('background_check_status', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('wallet_balance_cents', sa.Integer(), nullable=False),
    sa.Column('fleetbase_driver_id', sa.String(length=128), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('performance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_clerk_user_id'), 'drivers', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=False)
    op.create_index(op.f('ix_drivers_fleetbase_driver_id'), 'drivers', ['fleetbase_driver_id'], unique=False)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_table('fleetbase_sync_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('fleetbase_order_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleetbase_sync_audit_direction'), 'fleetbase_sync_audit', ['direction'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_audit_kind'), 'fleetbase_sync_audit', ['kind'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_audit_order_id'), 'fleetbase_sync_audit', ['order_id'], unique=False)
    op.create_table('fleetbase_sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('fleetbase_order_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleetbase_sync_jobs_direction'), 'fleetbase_sync_jobs', ['direction'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_jobs_fleetbase_order_id'), 'fleetbase_sync_jobs', ['fleetbase_order_id'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_jobs_idempotency_key'), 'fleetbase_sync_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_jobs_kind'), 'fleetbase_sync_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_jobs_next_attempt_at'), 'fleetbase_sync_jobs', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_jobs_order_id'), 'fleetbase_sync_jobs', ['order_id'], unique=False)
    op.create_index(op.f('ix_fleetbase_sync_jobs_status'), 'fleetbase_sync_jobs', ['status'], unique=False)
    op.create_table('identity_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=36), nullable=False),
    sa.Column('platform_org_id', sa.String(length=128), nullable=True),
    sa.Column('fleetbase_user_uuid', sa.String(length=128), nullable=True),
    sa.Column('fleetbase_roles', sa.JSON(), nullable=True),
    sa.Column('fleetbase_permissions', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_links_clerk_user_id'), 'identity_links', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_identity_links_email'), 'identity_links', ['email'], unique=False)
    op.create_index(op.f('ix_identity_links_fleetbase_user_uuid'), 'identity_links', ['fleetbase_user_uuid'], unique=False)
    op.create_index(op.f('ix_identity_links_platform_user_id'), 'identity_links', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_identity_links_user_type'), 'identity_links', ['user_type'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_table('merchant_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('minimum_monthly_commitment_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_contracts_merchant_id'), 'merchant_contracts', ['merchant_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('clerk_org_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('payment_terms', sa.String(length=16), nullable=False),
    sa.Column('credit_limit_cents', sa.Integer(), nullable=True),
    sa.Column('hst_number', sa.String(length=32), nullable=True),
    sa.Column('business_number', sa.String(length=32), nullable=True),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('pricing_config', sa.JSON(), nullable=False),
    sa.Column('preferred_vehicles', sa.JSON(), nullable=True),
    sa.Column('delivery_zones', sa.JSON(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_clerk_org_id'), 'merchants', ['clerk_org_id'], unique=True)
    op.create_index(op.f('ix_merchants_email'), 'merchants', ['email'], unique=False)
    op.create_index(op.f('ix_merchants_status'), 'merchants', ['status'], unique=False)
    op.create_table('notification_delivery_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_delivery_logs_channel'), 'notification_delivery_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_template'), 'notification_delivery_logs', ['template'], unique=False)
    op.create_table('pricing_tariffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tariff_type', sa.String(length=32), nullable=False),
    sa.Column('vehicle_class', sa.String(length=32), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('base_cents', sa.Integer(), nullable=False),
    sa.Column('per_km_cents', sa.Integer(), nullable=False),
    sa.Column('fuel_surcharge_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_tariffs_merchant_id'), 'pricing_tariffs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_pricing_tariffs_tariff_type'), 'pricing_tariffs', ['tariff_type'], unique=False)
    op.create_table('pricing_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bounds', sa.JSON(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_zones_code'), 'pricing_zones', ['code'], unique=True)
    op.create_table('promotions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('promotion_type', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_merchant_id'), 'promotions', ['merchant_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_customer_id'), 'support_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_driver_id'), 'support_tickets', ['driver_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_merchant_id'), 'support_tickets', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_order_id'), 'support_tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('visitor_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('browser', sa.String(length=128), nullable=True),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('quote_generated', sa.Boolean(), nullable=False),
    sa.Column('last_quote_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_import_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('order_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_import_jobs_merchant_id'), 'bulk_import_jobs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_bulk_import_jobs_status'), 'bulk_import_jobs', ['status'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('linkedin', sa.String(length=512), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_company_id'), 'crm_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_email'), 'crm_contacts', ['email'], unique=False)
    op.create_table('crm_deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('pipeline', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('expected_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('competitor', sa.String(length=255), nullable=True),
    sa.Column('reason_lost', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_deals_company_id'), 'crm_deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_owner_id'), 'crm_deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_stage'), 'crm_deals', ['stage'], unique=False)
    op.create_table('driver_bonuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_bonuses_driver_id'), 'driver_bonuses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_bonuses_status'), 'driver_bonuses', ['status'], unique=False)
    op.create_table('driver_incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_incidents_driver_id'), 'driver_incidents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_incidents_incident_type'), 'driver_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_driver_incidents_order_id'), 'driver_incidents', ['order_id'], unique=False)
    op.create_index(op.f('ix_driver_incidents_status'), 'driver_incidents', ['status'], unique=False)
    op.create_table('driver_location_pings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_location_pings_driver_id'), 'driver_location_pings', ['driver_id'], unique=False)
    op.create_table('driver_offline_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_offline_actions_action_type'), 'driver_offline_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_driver_offline_actions_driver_id'), 'driver_offline_actions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_offline_actions_status'), 'driver_offline_actions', ['status'], unique=False)
    op.create_table('driver_payouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_payouts_driver_id'), 'driver_payouts', ['driver_id'], unique=False)
    op.create_table('driver_wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('tx_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('balance_after_cents', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_wallet_transactions_driver_id'), 'driver_wallet_transactions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_wallet_transactions_reference_id'), 'driver_wallet_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_driver_wallet_transactions_tx_type'), 'driver_wallet_transactions', ['tx_type'], unique=False)
    op.create_table('merchant_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_api_keys_key_prefix'), 'merchant_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_merchant_api_keys_merchant_id'), 'merchant_api_keys', ['merchant_id'], unique=False)
    op.create_table('merchant_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_audit_logs_action'), 'merchant_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_merchant_audit_logs_merchant_id'), 'merchant_audit_logs', ['merchant_id'], unique=False)
    op.create_table('merchant_booking_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_booking_templates_merchant_id'), 'merchant_booking_templates', ['merchant_id'], unique=False)
    op.create_table('merchant_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('default_address', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_recipients_merchant_id'), 'merchant_recipients', ['merchant_id'], unique=False)
    op.create_table('merchant_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_users_clerk_user_id'), 'merchant_users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_merchant_users_merchant_id'), 'merchant_users', ['merchant_id'], unique=False)
    op.create_table('merchant_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_webhooks_merchant_id'), 'merchant_webhooks', ['merchant_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('anonymous_session_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('pickup', sa.JSON(), nullable=False),
    sa.Column('dropoff', sa.JSON(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=32), nullable=False),
    sa.Column('package_type', sa.String(length=64), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=128), nullable=True),
    sa.Column('declared_value_cents', sa.Integer(), nullable=True),
    sa.Column('additional_stops', sa.JSON(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('visitor_session_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schedule_mode', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pricing_breakdown', sa.JSON(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('consent', sa.JSON(), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_anonymous_session_id'), 'quotes', ['anonymous_session_id'], unique=False)
    op.create_index(op.f('ix_quotes_state'), 'quotes', ['state'], unique=False)
    op.create_index(op.f('ix_quotes_visitor_session_id'), 'quotes', ['visitor_session_id'], unique=False)
    op.create_table('saved_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('address_type', sa.String(length=32), nullable=False),
    sa.Column('formatted', sa.String(length=512), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_addresses_merchant_id'), 'saved_addresses', ['merchant_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_class', sa.String(length=32), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('make_model', sa.String(length=128), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('compliance_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fleetbase_vehicle_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_table('booking_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=False),
    sa.Column('pickup', sa.JSON(), nullable=True),
    sa.Column('dropoff', sa.JSON(), nullable=True),
    sa.Column('additional_stops', sa.JSON(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=32), nullable=True),
    sa.Column('package_type', sa.String(length=64), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=128), nullable=True),
    sa.Column('declared_value_cents', sa.Integer(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('pricing_breakdown', sa.JSON(), nullable=True),
    sa.Column('taxes_cents', sa.Integer(), nullable=False),
    sa.Column('discounts_cents', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('estimated_pickup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_mode', sa.String(length=16), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_drafts_booking_id'), 'booking_drafts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_drafts_customer_id'), 'booking_drafts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_booking_drafts_order_id'), 'booking_drafts', ['order_id'], unique=False)
    op.create_index(op.f('ix_booking_drafts_quote_id'), 'booking_drafts', ['quote_id'], unique=True)
    op.create_index(op.f('ix_booking_drafts_session_id'), 'booking_drafts', ['session_id'], unique=False)
    op.create_index(op.f('ix_booking_drafts_state'), 'booking_drafts', ['state'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('tracking_number', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('payment_terms', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('fleetbase_order_id', sa.String(length=128), nullable=True),
    sa.Column('assigned_driver_id', sa.String(length=36), nullable=True),
    sa.Column('pickup', sa.JSON(), nullable=False),
    sa.Column('dropoff', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('internal_reference', sa.String(length=128), nullable=True),
    sa.Column('purchase_order_number', sa.String(length=128), nullable=True),
    sa.Column('cost_centre', sa.String(length=64), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_assigned_driver_id'), 'orders', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_orders_fleetbase_order_id'), 'orders', ['fleetbase_order_id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_state'), 'orders', ['state'], unique=False)
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=True)
    op.create_table('booking_draft_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_draft_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('event_label', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_draft_id'], ['booking_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_draft_audits_booking_draft_id'), 'booking_draft_audits', ['booking_draft_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_number', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_state'), 'bookings', ['state'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('receipt_number', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('fees_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stripe_receipt_url', sa.String(length=512), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_receipt_number'), 'invoices', ['receipt_number'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_event_type'), 'order_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('order_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reported_by_type', sa.String(length=32), nullable=False),
    sa.Column('reported_by_id', sa.String(length=128), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_exceptions_order_id'), 'order_exceptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_exceptions_type'), 'order_exceptions', ['type'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_reference', sa.String(length=32), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_payments_quote_id'), 'payments', ['quote_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_quote_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_exceptions_type'), table_name='order_exceptions')
    op.drop_index(op.f('ix_order_exceptions_order_id'), table_name='order_exceptions')
    op.drop_table('order_exceptions')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_event_type'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_invoices_receipt_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_bookings_state'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_booking_draft_audits_booking_draft_id'), table_name='booking_draft_audits')
    op.drop_table('booking_draft_audits')
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_fleetbase_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_assigned_driver_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_booking_drafts_state'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_session_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_quote_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_order_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_customer_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_booking_id'), table_name='booking_drafts')
    op.drop_table('booking_drafts')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_saved_addresses_merchant_id'), table_name='saved_addresses')
    op.drop_table('saved_addresses')
    op.drop_index(op.f('ix_quotes_visitor_session_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_state'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_anonymous_session_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_merchant_webhooks_merchant_id'), table_name='merchant_webhooks')
    op.drop_table('merchant_webhooks')
    op.drop_index(op.f('ix_merchant_users_merchant_id'), table_name='merchant_users')
    op.drop_index(op.f('ix_merchant_users_clerk_user_id'), table_name='merchant_users')
    op.drop_table('merchant_users')
    op.drop_index(op.f('ix_merchant_recipients_merchant_id'), table_name='merchant_recipients')
    op.drop_table('merchant_recipients')
    op.drop_index(op.f('ix_merchant_booking_templates_merchant_id'), table_name='merchant_booking_templates')
    op.drop_table('merchant_booking_templates')
    op.drop_index(op.f('ix_merchant_audit_logs_merchant_id'), table_name='merchant_audit_logs')
    op.drop_index(op.f('ix_merchant_audit_logs_action'), table_name='merchant_audit_logs')
    op.drop_table('merchant_audit_logs')
    op.drop_index(op.f('ix_merchant_api_keys_merchant_id'), table_name='merchant_api_keys')
    op.drop_index(op.f('ix_merchant_api_keys_key_prefix'), table_name='merchant_api_keys')
    op.drop_table('merchant_api_keys')
    op.drop_index(op.f('ix_driver_wallet_transactions_tx_type'), table_name='driver_wallet_transactions')
    op.drop_index(op.f('ix_driver_wallet_transactions_reference_id'), table_name='driver_wallet_transactions')
    op.drop_index(op.f('ix_driver_wallet_transactions_driver_id'), table_name='driver_wallet_transactions')
    op.drop_table('driver_wallet_transactions')
    op.drop_index(op.f('ix_driver_payouts_driver_id'), table_name='driver_payouts')
    op.drop_table('driver_payouts')
    op.drop_index(op.f('ix_driver_offline_actions_status'), table_name='driver_offline_actions')
    op.drop_index(op.f('ix_driver_offline_actions_driver_id'), table_name='driver_offline_actions')
    op.drop_index(op.f('ix_driver_offline_actions_action_type'), table_name='driver_offline_actions')
    op.drop_table('driver_offline_actions')
    op.drop_index(op.f('ix_driver_location_pings_driver_id'), table_name='driver_location_pings')
    op.drop_table('driver_location_pings')
    op.drop_index(op.f('ix_driver_incidents_status'), table_name='driver_incidents')
    op.drop_index(op.f('ix_driver_incidents_order_id'), table_name='driver_incidents')
    op.drop_index(op.f('ix_driver_incidents_incident_type'), table_name='driver_incidents')
    op.drop_index(op.f('ix_driver_incidents_driver_id'), table_name='driver_incidents')
    op.drop_table('driver_incidents')
    op.drop_index(op.f('ix_driver_bonuses_status'), table_name='driver_bonuses')
    op.drop_index(op.f('ix_driver_bonuses_driver_id'), table_name='driver_bonuses')
    op.drop_table('driver_bonuses')
    op.drop_index(op.f('ix_crm_deals_stage'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_owner_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_company_id'), table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_index(op.f('ix_crm_contacts_email'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_bulk_import_jobs_status'), table_name='bulk_import_jobs')
    op.drop_index(op.f('ix_bulk_import_jobs_merchant_id'), table_name='bulk_import_jobs')
    op.drop_table('bulk_import_jobs')
    op.drop_table('visitor_sessions')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_order_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_merchant_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_driver_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_customer_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_promotions_merchant_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_pricing_zones_code'), table_name='pricing_zones')
    op.drop_table('pricing_zones')
    op.drop_index(op.f('ix_pricing_tariffs_tariff_type'), table_name='pricing_tariffs')
    op.drop_index(op.f('ix_pricing_tariffs_merchant_id'), table_name='pricing_tariffs')
    op.drop_table('pricing_tariffs')
    op.drop_index(op.f('ix_notification_delivery_logs_template'), table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_channel'), table_name='notification_delivery_logs')
    op.drop_table('notification_delivery_logs')
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_email'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_clerk_org_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_merchant_contracts_merchant_id'), table_name='merchant_contracts')
    op.drop_table('merchant_contracts')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_identity_links_user_type'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_platform_user_id'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_fleetbase_user_uuid'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_email'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_clerk_user_id'), table_name='identity_links')
    op.drop_table('identity_links')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_status'), table_name='fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_order_id'), table_name='fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_next_attempt_at'), table_name='fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_kind'), table_name='fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_idempotency_key'), table_name='fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_fleetbase_order_id'), table_name='fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_jobs_direction'), table_name='fleetbase_sync_jobs')
    op.drop_table('fleetbase_sync_jobs')
    op.drop_index(op.f('ix_fleetbase_sync_audit_order_id'), table_name='fleetbase_sync_audit')
    op.drop_index(op.f('ix_fleetbase_sync_audit_kind'), table_name='fleetbase_sync_audit')
    op.drop_index(op.f('ix_fleetbase_sync_audit_direction'), table_name='fleetbase_sync_audit')
    op.drop_table('fleetbase_sync_audit')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_fleetbase_driver_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_clerk_user_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_driver_stop_meta_order_id'), table_name='driver_stop_meta')
    op.drop_index(op.f('ix_driver_stop_meta_driver_id'), table_name='driver_stop_meta')
    op.drop_table('driver_stop_meta')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_aggregate_id'), table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_index(op.f('ix_customers_visitor_session_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_reference'), table_name='customers')
    op.drop_index(op.f('ix_customers_clerk_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_crm_tasks_status'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_merchant_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_lead_id'), table_name='crm_tasks')
    op.drop_table('crm_tasks')
    op.drop_index(op.f('ix_crm_sales_tasks_task_type'), table_name='crm_sales_tasks')
    op.drop_index(op.f('ix_crm_sales_tasks_status'), table_name='crm_sales_tasks')
    op.drop_index(op.f('ix_crm_sales_tasks_entity_id'), table_name='crm_sales_tasks')
    op.drop_index(op.f('ix_crm_sales_tasks_deal_id'), table_name='crm_sales_tasks')
    op.drop_index(op.f('ix_crm_sales_tasks_company_id'), table_name='crm_sales_tasks')
    op.drop_index(op.f('ix_crm_sales_tasks_assigned_to'), table_name='crm_sales_tasks')
    op.drop_table('crm_sales_tasks')
    op.drop_index(op.f('ix_crm_quotations_status'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_quote_number'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_deal_id'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_company_id'), table_name='crm_quotations')
    op.drop_table('crm_quotations')
    op.drop_index(op.f('ix_crm_notes_entity_id'), table_name='crm_notes')
    op.drop_table('crm_notes')
    op.drop_index(op.f('ix_crm_leads_status'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_source'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_email'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_deal_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_company_name'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_company_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_assigned_to'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_invoices_status'), table_name='crm_invoices')
    op.drop_index(op.f('ix_crm_invoices_invoice_number'), table_name='crm_invoices')
    op.drop_index(op.f('ix_crm_invoices_company_id'), table_name='crm_invoices')
    op.drop_table('crm_invoices')
    op.drop_index(op.f('ix_crm_documents_entity_type'), table_name='crm_documents')
    op.drop_index(op.f('ix_crm_documents_entity_id'), table_name='crm_documents')
    op.drop_index(op.f('ix_crm_documents_category'), table_name='crm_documents')
    op.drop_table('crm_documents')
    op.drop_index(op.f('ix_crm_contracts_status'), table_name='crm_contracts')
    op.drop_index(op.f('ix_crm_contracts_deal_id'), table_name='crm_contracts')
    op.drop_index(op.f('ix_crm_contracts_contract_number'), table_name='crm_contracts')
    op.drop_index(op.f('ix_crm_contracts_company_id'), table_name='crm_contracts')
    op.drop_table('crm_contracts')
    op.drop_index(op.f('ix_crm_companies_owner_id'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_merchant_status'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_merchant_id'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_legal_name'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_industry'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_email'), table_name='crm_companies')
    op.drop_table('crm_companies')
    op.drop_index(op.f('ix_crm_activities_entity_type'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_entity_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_activity_type'), table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_order_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_billing_ledger_entries_payment_id'), table_name='billing_ledger_entries')
    op.drop_index(op.f('ix_billing_ledger_entries_order_id'), table_name='billing_ledger_entries')
    op.drop_index(op.f('ix_billing_ledger_entries_merchant_id'), table_name='billing_ledger_entries')
    op.drop_index(op.f('ix_billing_ledger_entries_kind'), table_name='billing_ledger_entries')
    op.drop_table('billing_ledger_entries')
    op.drop_index(op.f('ix_admin_users_fleetbase_user_uuid'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_clerk_user_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_abandoned_checkouts_quote_id'), table_name='abandoned_checkouts')
    op.drop_table('abandoned_checkouts')
    # ### end Alembic commands ###
